### ISSUE TITLE
Error in seqVCF2GDS(vcf.files, gds.file, verbose = FALSE)

### ISSUE THREAD

**Issue by Bulouere** [smgogarten/GENESIS#92]
Hi,
I get an error when I'm trying to convert from a vcf file to a gds file using the SeqArray package. Here is my code and the error message. 
> gds.file <- tempfile()
> seqVCF2GDS(vcf.files, gds.file, verbose=FALSE)
Error in seqVCF2GDS(vcf.files, gds.file, verbose = FALSE) : 
  FORMAT ID 'QSS' (Number=A) should have 1 value(s) but receives 2, please consider revising it to 'Number=.'.
FILE: C:\Users\bwodu1\OneDrive - Johns Hopkins\Yegna Lab\u01\test_vcf\55488_60663_Cancer_vs_55488_60664_Benign_mutect2_passed.vcf
LINE: 66, COLUMN: 10, 0/1:23,14:0.381

**Comment by smgogarten** [comment]
As this is an issue with the SeqArray package, please report it there instead: https://github.com/zhengxwen/SeqArray/issues
