### ISSUE TITLE
Estimate PVE 

### ISSUE THREAD

**Issue by MARCPUCV** [smgogarten/GENESIS#96]
Hi,
I would like to know how the PVE is calculated. I have the data from the GMMAT package and I don't know how to estimate the PVE of the significant snps. I saw that with your package it can be calculated but I have had problems with the installation of the GENESIS and GWASTools packages. Thank you very much.

Best regards!!
Angélica

**Comment by mconomos** [comment]
Hello,
In GENESIS, the individual variant PVE is approximated from the score test statistic and the residual sum of squares for the null model. Specifically, the approximated PVE = (Score.Stat)^2/RSS0, where Score.Stat = score/SE(score) and RSS0 is the residual sum of squares from the null model. 

For details of the explanation/derivation, please see the section "Proportion of Variance Explained Jointly by a set of variants" from the supplemental materials of this manuscript: https://pubmed.ncbi.nlm.nih.gov/33887194/
