### ISSUE TITLE
pcrelate REDUCE error while calculating individual AF betas

### ISSUE THREAD

**Issue by BEFH** [smgogarten/GENESIS#98]
I have a sample of 49227 individuals, with 4626 of those individuals related to each other.

When I run pcrelate, I get the following output:

```
Using 1 CPU cores
49227 samples to be included in the analysis, split into 10 blocks...
Using 62 CPU cores
Betas for 2 PC(s) will be calculated using 44601 samples in training.set...
Calculating Indivdiual-Specific Allele Frequency betas for 375415 SNPs in 38 blocks...
Error in REDUCE(env[["value"]], env[[idx]][[i]]) : 
  Input is matrix but should be a plain list of items to be stacked
```

This is with this command:

```r
pcrel_initial <- pcrelate(gdsobj = genoiter,
                          pcs = pcmat_initial[, 1:2],
                          training.set = parts$unrels$IID,
                          small.samp.correct = nrow(fam) < 5000,
                          ibd.probs = FALSE,
                          BPPARAM = BiocParallel::SerialParam())
```

`genoiter` looks like this:

```
> str(genoiter)
Formal class 'GenotypeBlockIterator' [package ""] with 6 slots
  ..@ snpBlock  : int 10000
  ..@ snpFilter :List of 38
  .. ..$ 1 : int [1:10000] 1 2 3 4 5 6 7 8 9 10 ...
  .. ..$ 2 : int [1:10000] 10001 10002 10003 10004 10005 10006 10007 10008 10009 10010 ...
  .. ..$ 3 : int [1:10000] 20001 20002 20003 20004 20005 20006 20007 20008 20009 20010 ...
  .. ..$ 4 : int [1:10000] 30001 30002 30003 30004 30005 30006 30007 30008 30009 30010 ...
  .. ..$ 5 : int [1:10000] 40001 40002 40003 40004 40005 40006 40007 40008 40009 40010 ...
  .. ..$ 6 : int [1:10000] 50001 50002 50003 50004 50005 50006 50007 50008 50009 50010 ...
  .. ..$ 7 : int [1:10000] 60001 60002 60003 60004 60005 60006 60007 60008 60009 60010 ...
  .. ..$ 8 : int [1:10000] 70001 70002 70003 70004 70005 70006 70007 70008 70009 70010 ...
  .. ..$ 9 : int [1:10000] 80001 80002 80003 80004 80005 80006 80007 80008 80009 80010 ...
  .. ..$ 10: int [1:10000] 90001 90002 90003 90004 90005 90006 90007 90008 90009 90010 ...
  .. ..$ 11: int [1:10000] 100001 100002 100003 100004 100005 100006 100007 100008 100009 100010 ...
  .. ..$ 12: int [1:10000] 110001 110002 110003 110004 110005 110006 110007 110008 110009 110010 ...
  .. ..$ 13: int [1:10000] 120001 120002 120003 120004 120005 120006 120007 120008 120009 120010 ...
  .. ..$ 14: int [1:10000] 130001 130002 130003 130004 130005 130006 130007 130008 130009 130010 ...
  .. ..$ 15: int [1:10000] 140001 140002 140003 140004 140005 140006 140007 140008 140009 140010 ...
  .. ..$ 16: int [1:10000] 150001 150002 150003 150004 150005 150006 150007 150008 150009 150010 ...
  .. ..$ 17: int [1:10000] 160001 160002 160003 160004 160005 160006 160007 160008 160009 160010 ...
  .. ..$ 18: int [1:10000] 170001 170002 170003 170004 170005 170006 170007 170008 170009 170010 ...
  .. ..$ 19: int [1:10000] 180001 180002 180003 180004 180005 180006 180007 180008 180009 180010 ...
  .. ..$ 20: int [1:10000] 190001 190002 190003 190004 190005 190006 190007 190008 190009 190010 ...
  .. ..$ 21: int [1:10000] 200001 200002 200003 200004 200005 200006 200007 200008 200009 200010 ...
  .. ..$ 22: int [1:10000] 210001 210002 210003 210004 210005 210006 210007 210008 210009 210010 ...
  .. ..$ 23: int [1:10000] 220001 220002 220003 220004 220005 220006 220007 220008 220009 220010 ...
  .. ..$ 24: int [1:10000] 230001 230002 230003 230004 230005 230006 230007 230008 230009 230010 ...
  .. ..$ 25: int [1:10000] 240001 240002 240003 240004 240005 240006 240007 240008 240009 240010 ...
  .. ..$ 26: int [1:10000] 250001 250002 250003 250004 250005 250006 250007 250008 250009 250010 ...
  .. ..$ 27: int [1:10000] 260001 260002 260003 260004 260005 260006 260007 260008 260009 260010 ...
  .. ..$ 28: int [1:10000] 270001 270002 270003 270004 270005 270006 270007 270008 270009 270010 ...
  .. ..$ 29: int [1:10000] 280001 280002 280003 280004 280005 280006 280007 280008 280009 280010 ...
  .. ..$ 30: int [1:10000] 290001 290002 290003 290004 290005 290006 290007 290008 290009 290010 ...
  .. ..$ 31: int [1:10000] 300001 300002 300003 300004 300005 300006 300007 300008 300009 300010 ...
  .. ..$ 32: int [1:10000] 310001 310002 310003 310004 310005 310006 310007 310008 310009 310010 ...
  .. ..$ 33: int [1:10000] 320001 320002 320003 320004 320005 320006 320007 320008 320009 320010 ...
  .. ..$ 34: int [1:10000] 330001 330002 330003 330004 330005 330006 330007 330008 330009 330010 ...
  .. ..$ 35: int [1:10000] 340001 340002 340003 340004 340005 340006 340007 340008 340009 340010 ...
  .. ..$ 36: int [1:10000] 350001 350002 350003 350004 350005 350006 350007 350008 350009 350010 ...
  .. ..$ 37: int [1:10000] 360001 360002 360003 360004 360005 360006 360007 360008 360009 360010 ...
  .. ..$ 38: int [1:5415] 370001 370002 370003 370004 370005 370006 370007 370008 370009 370010 ...
  ..@ lastFilter:<environment: 0x56544778c8f0> 
  ..@ data      :Formal class 'GdsGenotypeReader' [package "GWASTools"] with 15 slots
  .. .. ..@ snpIDvar     : chr "snp.id"
  .. .. ..@ chromosomeVar: chr "snp.chromosome"
  .. .. ..@ positionVar  : chr "snp.position"
  .. .. ..@ scanIDvar    : chr "sample.id"
  .. .. ..@ genotypeVar  : chr "genotype"
  .. .. ..@ alleleVar    : chr "snp.allele"
  .. .. ..@ autosomeCode : int [1:22] 1 2 3 4 5 6 7 8 9 10 ...
  .. .. ..@ XchromCode   : int 23
  .. .. ..@ YchromCode   : int 25
  .. .. ..@ XYchromCode  : int 24
  .. .. ..@ MchromCode   : int 26
  .. .. ..@ genotypeDim  : chr "scan,snp"
  .. .. ..@ missingValue : int 3
  .. .. ..@ filename     : chr "results/intermediate/post-impute_filter/output/imputed_filtered_PCApre.gds"
  .. .. ..@ handler      :List of 5
  .. .. .. ..$ filename: chr "/sc/arion/projects/load/data-ext/ADGC/2021_freeze/processed/071822/results/intermediate/post-impute_filter/outp"| __truncated__
  .. .. .. ..$ id      : int 0
  .. .. .. ..$ ptr     :<externalptr> 
  .. .. .. ..$ root    : 'gdsn.class' raw [1:20] 00 00 00 00 ...
  .. .. .. ..$ readonly: logi TRUE
  .. .. .. ..- attr(*, "class")= chr "gds.class"
  ..@ snpAnnot  : NULL
  ..@ scanAnnot : NULL
```

`pcmat_initial` looks like this (censored):

```
> str(pcmat_initial)
 num [1:49227, 1:16] -0.0095 -0.00484 -0.0097 -0.00814 -0.01007 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:49227] "foo-AA--bar" "foo2-AA--bar2" "foo3-AA--bar3" "foo4-AA--bar4" ...
  ..$ : NULL
```

Finally, `training.set` is a character vector of IDs.

I get the same issue when just running `calcISAFBeta`.

The command is this:

```r
calcISAFBeta(gdsobj = genoiter,
             pcs = pcmat_initial[, 1:2],
             sample.include = iids,
             training.set = parts$unrels$IID,
             BPPARAM = BiocParallel::SerialParam())
```

The output is this:

```
Using 1 CPU cores
Betas for 2 PC(s) will be calculated using 44601 samples in training.set...
Calculating Indivdiual-Specific Allele Frequency betas for 375415 SNPs in 38 blocks...
Error in REDUCE(env[["value"]], env[[idx]][[i]]) : 
  Input is matrix but should be a plain list of items to be stacked
```

Subsampling then running is sucessful.

```
> pcrel_initial_samp <- pcrelate(gdsobj = genoiter,
+                                sample.include = iids_samp,
+                                pcs = pcmat_initial[rownames(pcmat_initial) %in% iids_samp, 1:2],
+                                training.set = parts$unrels$IID[parts$unrels$IID %in% iids_samp],
+                                small.samp.correct = TRUE,
+                                ibd.probs = FALSE,
+                                BPPARAM = BiocParallel::SerialParam())
Using 1 CPU cores
4000 samples to be included in the analysis...
Betas for 2 PC(s) will be calculated using 3641 samples in training.set...
Running PC-Relate analysis for 4000 samples using 375415 SNPs in 38 blocks...
Performing Small Sample Correction...
>
```

Finally, setting the `sample.block.size` to 50000 seemed initially successful, but seems to have hung. At its maximum, it used 478.3 GiB of memory and is now down to 85.3 GiB, but it hasn't completed and CPU usage is at 0.

I will attach my sessioninfo when I get a chance.

**Comment by BEFH** [comment]
Here's my `sessionInfo()`:

```
> sessionInfo()
R version 4.1.3 (2022-03-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

Matrix products: default
BLAS/LAPACK: /sc/arion/work/fultob01/conda/envs/genesis/lib/libopenblasp-r0.3.21.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] GWASTools_1.40.0    Biobase_2.54.0      BiocGenerics_0.40.0 dplyr_1.0.10        readr_2.1.2         tibble_3.1.8        SNPRelate_1.28.0   
[8] gdsfmt_1.30.0       GENESIS_2.24.1     

loaded via a namespace (and not attached):
 [1] tidyr_1.2.1            bit64_4.0.5            splines_4.1.3          assertthat_0.2.1       stats4_4.1.3           blob_1.2.3            
 [7] GenomeInfoDbData_1.2.7 GWASExactHW_1.01       pillar_1.8.1           RSQLite_2.2.8          backports_1.4.1        lattice_0.20-45       
[13] quantreg_5.94          glue_1.6.2             GenomicRanges_1.46.1   XVector_0.34.0         colorspace_2.0-3       sandwich_3.0-2        
[19] Matrix_1.4-1           timeDate_4021.104      pkgconfig_2.0.3        broom_1.0.1            SparseM_1.81           zlibbioc_1.40.0       
[25] purrr_0.3.4            tzdb_0.3.0             SeqVarTools_1.32.0     BiocParallel_1.28.3    MatrixModels_0.5-0     mgcv_1.8-40           
[31] generics_0.1.3         IRanges_2.28.0         ellipsis_0.3.2         cachem_1.0.6           withr_2.5.0            formula.tools_1.7.1   
[37] cli_3.4.0              survival_3.4-0         magrittr_2.0.3         crayon_1.5.1           memoise_2.0.1          mice_3.14.0           
[43] fansi_1.0.3            operator.tools_1.6.3   nlme_3.1-159           MASS_7.3-58.1          SeqArray_1.34.0        tools_4.1.3           
[49] data.table_1.14.2      hms_1.1.2              lifecycle_1.0.2        S4Vectors_0.32.4       Biostrings_2.62.0      compiler_4.1.3        
[55] GenomeInfoDb_1.30.0    logistf_1.24.1         rlang_1.0.5            grid_4.1.3             RCurl_1.98-1.8         rstudioapi_0.14       
[61] bitops_1.0-7           DNAcopy_1.68.0         DBI_1.1.3              R6_2.5.1               zoo_1.8-11             lubridate_1.8.0       
[67] fastmap_1.1.0          bit_4.0.4              utf8_1.2.2             parallel_4.1.3         Rcpp_1.0.9             quantsmooth_1.60.0    
[73] vctrs_0.4.1            tidyselect_1.1.2       lmtest_0.9-40
```

**Comment by smgogarten** [comment]
Thanks for the detailed report. This bug was fixed recently (commit 6c45525), so please install the latest version of GENESIS.

Additionally, the built-in parallelization in `pcrelate` is over SNPs, not samples, so with nearly 50k samples it might be worthwhile for you to speed up your calculations by running sample blocks in parallel. This takes a bit more work to set up, but #38 has an outline of how you could do it.

**Comment by BEFH** [comment]
Thanks! I actually found what I thought might be a reference to the fix last night and upgraded to the latest version. It seems to have worked, but I'll have to figure out how to make it reproducible in my pipeline. I cannot get R 4.2 though conda-forge, which is what I generally use.

A couple of things are still extremely slow and memory intensive with the large sample size:

*  The KING matrix takes days to read in if pre-calculated with the KING software because of the clustering step. I used KING robust for that. Should I have used IBDseg or related instead? It seems to be faster to actually regenerate the inferences in snprelate, which doesn't seem right. It also takes massive amounts of memory even with internal generation. I worry it won't actually be possible with sample sizes that are any larger.
*  pcrelateToMatrix() and kingToMatrix() still take a super long time regardless.
*  I'm doing a multi-step iterative process from KING -> pcairPartition -> custom snprelate PCA (random) -> pcrelate -> pcairPartition -> custom snprelate PCA (regular) -> pcrelate. I am using unpruned SNPs for the initial KING because that is recommended in their papers, and I am using pruned genotypes for everything else (375415 SNPs). Is there anything at all I can do to speed things up?

**Comment by smgogarten** [comment]
We use KING IBDseg with sample sizes that large. It's faster to run, and it doesn't write out results for pairs below a certain threshold, so it's much faster to read in the results. The one tricky thing is you need to use the `sample.include` argument to `kingToMatrix` to get a matrix with all your samples included; otherwise samples with no relatives in the KING IBDseg output get dropped.

I also recommend using sparse matrices if you're not already. Set the `thresh` argument to something that captures the level of relatedness in your sample set (3rd or 4th degree relatives are both reasonable choices), and all pairwise values in the matrix with relatedness less than that threshold will be set to zero. This reduces the memory usage immensely; instead of storing NxN values, the sparse Matrix object only stores the non-zero values and their indices. Computation time is much faster as well.

**Comment by BEFH** [comment]
Thanks for your prompt responses here. I'm actually quite confused by this, based on the documentation and my understanding of how the partitioning works. Don't I (for the initial KING matrix at least) need negative kinship coefficients in order to calculate divergence for maximally ancestrally divergent unrelated samples? Wouldn't IBDseg not writing out highly divergent samples also be problematic for the same reason?

If `thresh` is just for the subsequent `pcrelate` results, that makes a lot more sense, though, since I'm still using KING for the divergence calculations.

**Comment by smgogarten** [comment]
Yes, you're right. The sparse matrix works for the kinship but not for the ancestry divergence (and those can be two different matrices). When we got up to really huge sample sizes (100k) we actually dropped the divergence matrix and found that it worked just as well, since there were enough samples that the ancestry space was well populated even when the code is not making a special effort to select divergent samples.

One other thing that can help if you want to keep the divergence matrix is to store it in GDS instead of in an R object. That way you're not reading the entire matrix into memory at once; just the sample pairs for each block. If you use the SNPRelate implementation of KING robust, the GENESIS function `kin2gds` will write the result to a GDS file.

**Comment by BEFH** [comment]
Sorry, I'm really asking a lot of questions here. `--ibdseg` does not have negative kinship coefficients. That shouldn't be an issue with reading it in, but what do I set the `div.thresh` to? It's -2^(-11/2) by default, so zero pairs should be classified as divergent.

This is the formula used by `--ibdseg` showing the impossibility of negative coefficients:

> IBD1Seg: Total length of IBD1 segments divided by total length of all segments, estimate of π1=Pr(IBD=1)
> IBD2Seg: Total length of IBD2 segments divided by total length of all segments, estimate of π2=Pr(IBD=2)
> PropIBD: Proportion of genomes shared identical-by-descent, estimated by IBD2Seg + IBD1Seg/2, estimate of π=π2+π1/2

I saw these PRs, but I'm still trying to figure out what to do:

#18 #1

**Comment by smgogarten** [comment]
You can use the output of `KING --ibdseg` as the kinship matrix (`kinobj`), but not as the divergence matrix (`divobj`). For the divergence matrix, you do need `KING --robust` output with negative kinship coefficients. However, you can omit both `divobj` and `div.thresh` in a call to `pcairPartition`, and it will select unrelated samples without considering ancestry divergence.
